server:
  port: 8080
spring:
#数据库配置
  datasource:
    name: mysql_blog
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://139.199.122.47:3306/ning_blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: guotongning
      password: guotongning
  redis: #Redis配置
    jedis:
      pool:
        max-active: 8
    password: guotongning
    port: 6379
    host: 139.199.122.47
    database: 0
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    servlet:
      load-on-startup: 1
    static-path-pattern: classpath:/static/
  #devtools:
  #  restart:
  #    enabled: true
  #    additional-paths: src/main/java
  #    additional-exclude: classpath:/static/
mybatis: #mybatis配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ning.blog.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
